# Generated by Django 4.0.3 on 2023-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_remove_hats_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='import_href',
            field=models.CharField(default=' ', max_length=100, unique=True),
        ),
    ]
