# Generated by Django 4.0.3 on 2023-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_remove_locationvo_closet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='closet_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='locationvo',
            name='section_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='locationvo',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
